### ISSUE TITLE
information about devices and other configuration

### ISSUE THREAD

**Issue by headre** [zesenwu23/USL-VI-ReID#1]
Thanks for your excellent job! We are interested in this project and we wonder your devices for this job. 
When we tried doing reproduction work, we found that we can only achieve around 52% at Rank-1 for SYSU-MM01 but you can reach 57% in your log, and can you give me some suggestions on this result? By the way, our devices are 2 GPUs of V100-SXM2-32GB.

**Comment by zesenwu23** [comment]
Thanks for your question.
We run the code on 4 GPUS of RTX 3090, each with 24G memory. Considering the memory limitation, we cannot run the code with only 2 GPUs, so we don't know the difference in the results of 2 or 4 GPUs. Generally, we think that a difference of 1% or 2%  is acceptable for unsupervised tasks. 
Moreover, it may work if you run the code with the same environment and datasets as ours. Contact us if you have any questions.

**Comment by Velpro-collab** [comment]
IR Clustering criterion: eps: 0.600
RGB Clustering criterion: eps: 0.600
==> Create pseudo labels for unlabeled RGB data
Traceback (most recent call last):
  File "/media/lele/e/zzg/USL/train_sysu.py", line 1110, in <module>
    main()
  File "/media/lele/e/zzg/USL/train_sysu.py", line 377, in main
    main_worker_stage1(args,log_s1_name) # Stage 1
  File "/media/lele/e/zzg/USL/train_sysu.py", line 456, in main_worker_stage1
    features_rgb, labels_rgb = extract_features(model, cluster_loader_rgb, print_freq=50,mode=1)
  File "/media/lele/e/zzg/USL/clustercontrast/evaluators.py", line 43, in extract_features
    outputs = extract_cnn_feature(model, imgs, mode)
  File "/media/lele/e/zzg/USL/clustercontrast/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs, inputs, modal=mode)
  File "/home/lele/miniconda3/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lele/miniconda3/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/lele/miniconda3/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'modal'

Hello, the code has this problem, how to solve it?

**Comment by zesenwu23** [comment]
> IR Clustering criterion: eps: 0.600 RGB Clustering criterion: eps: 0.600 ==> Create pseudo labels for unlabeled RGB data Traceback (most recent call last): File "/media/lele/e/zzg/USL/train_sysu.py", line 1110, in main() File "/media/lele/e/zzg/USL/train_sysu.py", line 377, in main main_worker_stage1(args,log_s1_name) # Stage 1 File "/media/lele/e/zzg/USL/train_sysu.py", line 456, in main_worker_stage1 features_rgb, labels_rgb = extract_features(model, cluster_loader_rgb, print_freq=50,mode=1) File "/media/lele/e/zzg/USL/clustercontrast/evaluators.py", line 43, in extract_features outputs = extract_cnn_feature(model, imgs, mode) File "/media/lele/e/zzg/USL/clustercontrast/evaluators.py", line 25, in extract_cnn_feature outputs = model(inputs, inputs, modal=mode) File "/home/lele/miniconda3/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/home/lele/miniconda3/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward return self.module(*inputs[0], **kwargs[0]) File "/home/lele/miniconda3/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) TypeError: forward() got an unexpected keyword argument 'modal'
> 
> Hello, the code has this problem, how to solve it?

Hello, have you ever changed the code? We think this error happens when changing the model or relative functions.

**Comment by Velpro-collab** [comment]
> > IR Clustering criterion: eps: 0.600 RGB Clustering criterion: eps: 0.600 ==> Create pseudo labels for unlabeled RGB data Traceback (most recent call last): File "/media/lele/e/zzg/USL/train_sysu.py", line 1110, in main() File "/media/lele/e/zzg/USL/train_sysu.py", line 377, in main main_worker_stage1(args,log_s1_name) # Stage 1 File "/media/lele/e/zzg/USL/train_sysu.py", line 456, in main_worker_stage1 features_rgb, labels_rgb = extract_features(model, cluster_loader_rgb, print_freq=50,mode=1) File "/media/lele/e/zzg/USL/clustercontrast/evaluators.py", line 43, in extract_features outputs = extract_cnn_feature(model, imgs, mode) File "/media/lele/e/zzg/USL/clustercontrast/evaluators.py", line 25, in extract_cnn_feature outputs = model(inputs, inputs, modal=mode) File "/home/lele/miniconda3/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/home/lele/miniconda3/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward return self.module(*inputs[0], **kwargs[0]) File "/home/lele/miniconda3/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) TypeError: forward() got an unexpected keyword argument 'modal'
> > Hello, the code has this problem, how to solve it?
> 
> Hello, have you ever changed the code? We think this error happens when changing the model or relative functions.

您好，我没有改动任何代码，仅修改了自己的数据集路径

**Comment by vk-rrr** [comment]
请问解决了吗？应该怎么处理

**Comment by Velpro-collab** [comment]
> 请问解决了吗？应该怎么处理

未解决
