### ISSUE TITLE
在sysu上运行的时候模块一直出现这个问题，有什么解决方法吗

### ISSUE THREAD

**Issue by Dongly502** [zesenwu23/USL-VI-ReID#2]

**Comment by zesenwu23** [comment]
这个错误的出现，是因为RGB模态聚类的数量超过IR聚类数量的两倍。我们实现过程中，只写了两层循环，是因为我们观察到SYSU-MM01在经过第一阶段的训练之后，RGB模态聚类数量和IR模态聚类数量比较稳定，且不会超过两倍差距。但是您实现的条件有所不同，所以第一阶段可能无法达到要求，所以需要在第二阶段的代码做修改。具体来说，即对为进行匹配的RGB cluster进行新一轮匹配。
