### ISSUE TITLE
关于复现结果

### ISSUE THREAD

**Issue by hejiakia** [zesenwu23/USL-VI-ReID#8]
您好，感谢您提供的代码。有个问题想问您，我们在SYSU-MM01数据集上复现的结果和论文结果出入很大，想问问是什么原因呢。我们使用的是4张V100，batchsize==256，预训练模型也是从您给的网站下载的。
![1714976530266](https://github.com/zesenwu23/USL-VI-ReID/assets/118721878/43e4ecf2-4b76-452c-9ce7-c4357b8ae4b6)

**Comment by zesenwu23** [comment]
> 您好，感谢您提供的代码。有个问题想问您，我们在SYSU-MM01数据集上复现的结果和论文结果出入很大，想问问是什么原因呢。我们使用的是4张V100，batchsize==256，预训练模型也是从您给的网站下载的。 ![1714976530266](https://private-user-images.githubusercontent.com/118721878/328094370-43e4ecf2-4b76-452c-9ce7-c4357b8ae4b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjA5ODAsIm5iZiI6MTcxNTA2MDY4MCwicGF0aCI6Ii8xMTg3MjE4NzgvMzI4MDk0MzcwLTQzZTRlY2YyLTRiNzYtNDUyYy05Y2U3LWM0MzU3YjhhZTRiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwNTQ0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzIwM2RiOTNiY2ZjYzJlYzQ0MjFlNDU0ZDRkODI3YmRmMjMzZWQ4YmNiYTc3NTBiM2Y0NDRmNDhlZDE3OGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oJXUR8wKC20xO6ldhQLb4pdZ05enRdyyFhQYsePkpqA)

您好。从仅有的信息来看，您的结果与第一阶段的结果（Indoor Search）接近，因此目前推断是否仅仅做了第一阶段的训练，建议仔细检查一下。

抱歉较晚的回复，有更多即时问题请联系我。

**Comment by hejiakia** [comment]
您好，是的，现在已跑完第二阶段的训练，结果已达预期，抱歉当时还没仔细看代码

**Comment by zesenwu23** [comment]
> 您好，是的，现在已跑完第二阶段的训练，结果已达预期，抱歉当时还没仔细看代码

感谢关注，有更多即时问题请联系我。（zesenwu@whu.edu.cn)
